#!/bin/bash

SRC=attribute_parser.cpp
TGT=ap

if [ -f $TGT ]; then
	rm -f $TGT
fi

# Using Intel C++ compiler
icpx -Wall -std=c++17 -fsycl $SRC -o $TGT
# icpc -Wall -std=c++17 -diag-disable=10441 $SRC -o $TGT
